name: Jobs at Apple [Global]

on:
  schedule:
    - cron: '0 18 * * 2,4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: install python packages
        run: pip install -r requirements.txt
      - name: execute py script
        env:
          BOTPOST_API: ${{ secrets.BOTPOST_API }}
          BOTPOST_CHAT_ID: ${{ secrets.BOTPOST_CHAT_ID }}
        run: python3 Jobs.py -dv
      - name: commit files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'auto: Jobs at Apple'